# Generated by Django 3.1.5 on 2021-01-27 15:11

# Django
from django.db import migrations, models

# Third Party Libraries
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20210127_1329"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
